### ISSUE TITLE
No translate button appears

### ISSUE THREAD

**Issue by samuk** [humhub/translator-issues#1]
I have installed and activated the plugin.

I have put a valid Deepl API key in. 

I see no translate link on posts. Have I missed a step?

Error  Thu, 28 Apr 2022 11:50:07 +0000  translator
DeepL translation API response is not valid! ({"message":"Wrong endpoint. Use https://api-free.deepl.com"})

**Comment by luke-** [comment]
Are you using a free api key?

**Comment by samuk** [comment]
Yes.

But the path recommended in the module is now a 404 so I wonder if they have moved their API?

![api](https://user-images.githubusercontent.com/400875/166435216-e0491a59-2f10-4013-8a81-49a5f04e854d.png)

**Comment by luke-** [comment]
The current version doesn't support free api keys. There is a unreleased version which adds support for this keys. I'll release this version later today.

**Comment by samuk** [comment]
Thanks. I did try first with a paid key too (trial period) that didn't seem to work either.

I'll try the updated version later..

**Comment by luke-** [comment]
Please try 0.2.3

**Comment by samuk** [comment]
Thanks. Unfortunately, It's still not working on the free key. Should I try the paid key?

**Comment by samuk** [comment]
No error is given in the Humhub logs.

**Comment by samuk** [comment]
It's not working with either the free of paid key. 

It does seem like it's hitting the API though, this account is brand new and not connected with any other services.

![deepl](https://user-images.githubusercontent.com/400875/167019637-77274632-2703-453d-95d2-9f916443897f.png)

**Comment by yurabakhtin** [comment]
@luke- @samuk The "Translate" link is hidden if the message language is same as current user language, because no reason to translate, but the message language is detected by driver automatically and there may be some issues I think.
Please review my tests, and provide your samples for testing from our side:

User language is English:

![translator-en](https://user-images.githubusercontent.com/6995524/167445371-b9ab5681-9ad0-43c6-a5e7-bc423e2e5344.png)

User language is French:

![translator-fr](https://user-images.githubusercontent.com/6995524/167445452-aa34d474-9e61-41bb-b1d8-a8c827eee5e9.png)
