### ISSUE TITLE
Add support for Libretranslate

### ISSUE THREAD

**Issue by samuk** [humhub/translator-issues#5]
https://libretranslate.com/ seems to be improving to the point it's usable. Could this be added?

**Comment by dvn0** [comment]
This library may be useful: https://github.com/jefs42/libretranslate

Would love to help contribute to this, but since it's closed-source all we can do is "throw things over the fence".

**Comment by dvn0** [comment]
To provide a bit of information on the ostensible motivation for this feature request, for posterity:

LibreTranslate is a free software project that implements a language translation server which is self-hostable, and has a [well document](https://libretranslate.com/docs/) and standard REST API. This should not be particularly difficult to implement as an additional translation service backend to the Translator plugin. Since LibreTranslate can be self-hosted, this allows you to keep your HumHub posts and comments private within your own domain, instead of sending them to a 3rd party (such as DeepL or Google Translate).

**Comment by samuk** [comment]
Annoying that the licensing is a barrier to contribution here, particularly as a paid subscriber to the translate plugin. @luke- might you be able to give @dvn0 access to the repo under NDA or similar?

**Comment by luke-** [comment]
@samuk @dvn0 Thank you for your interest in integrating a new driver here.

Please send an e-mail to hello@humhub.com - we can then provide the GIT files or repo access.

**Comment by dvn0** [comment]
Thanks for following up. I sent an email yesterday.

**Comment by samuk** [comment]
If you need access to a libretranslate instance I could probably give access to ours, I imagine you already have access to one?

**Comment by dvn0** [comment]
Thanks @samuk. I'll let you know if I need that. May be helpful indeed, thanks! Waiting to hear back from the HumHub team, in the meantime.

**Comment by dvn0** [comment]
@luke- I'm sorry, I missed the notification for your invite. Can you resend?

**Comment by luke-** [comment]
@dvn0 No problem, I've just resend the invite.

**Comment by dvn0** [comment]
I've implemented a LibreTranslate driver, and @luke- made a new release which should be arriving in the marketplace at some point.

**Comment by luke-** [comment]
There is a problem with the deployment right now. However, the version should be available soon.

**Comment by samuk** [comment]
Nice! Looking forward to it

**Comment by dvn0** [comment]
AFAIK this was released back in May. See: https://marketplace.humhub.com/module/translator/changelog

The LibreTranslate support is not mentioned in the description of the module, but despite that I think this module could be closed.

**Comment by luke-** [comment]
@dvn0 Thanks for the hint. The updated translation is available with the next release.
